import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SidePanel from "./components/SidePanel";
import AuthProvider from "./auth/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next Budget",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <div className="flex">
            <SidePanel />
            <main className="p-5">{children}</main>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
